version: '3.8'
services:
  node:
    image: sigp/lighthouse:v2.1.5-modern
    restart: always
    command: |
      lighthouse beacon_node
      --network gnosis
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --eth1-blocks-per-log-query 256
      --datadir /home/.eth2/beaconchaindata
      --enr-address $PUBLIC_IP
      --enr-udp-port 12000
      --trusted-peers $TRUSTED_PEERS
      --checkpoint-sync-url $CHECKPOINT_URL
      --http
      --http-address 0.0.0.0
      --http-allow-origin *
      --metrics
      --metrics-address 0.0.0.0
      --metrics-allow-origin *
      --debug-level $LOG_LEVEL
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '5054:5054'
      - '5052:5052'
    volumes:
      - ./node_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
