version: '3.8'
services:
  node:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --enr-address $PUBLIC_IP
      --enr-udp-port 12000
      --metrics
      --metrics-address 0.0.0.0
      --metrics-allow-origin *
      --debug-level $LOG_LEVEL
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '5054:5054'
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
